# Concatinating

In [5]:
import pandas as pd
import numpy as np
from pandas import DataFrame,Series

In [6]:
a=np.arange(0,9).reshape(3,3)

In [7]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
np.concatenate([a,a],axis=0) # array is part of numpy
#row wise

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
np.concatenate([a,a],axis=1) #column wise

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [12]:
ser1=Series([0,1,2],index=['t','u','v'],)

In [14]:
ser1

t    0
u    1
v    2
dtype: int64

In [18]:
ser2=Series([3,4],index=list('xy'))

In [19]:
ser2

x    3
y    4
dtype: int64

In [20]:
np.concatenate([ser1,ser2],axis=0) # concatenate comes from numpy

array([0, 1, 2, 3, 4], dtype=int64)

In [23]:
pd.concat([ser1,ser2]) # concat is pandas function 
#AS SERIES COMES FROM PANDAS WE HAVE TO USE PANDAS FUNCTION AS CONCATENATE() WILL NOT BE USEFUL HERE

t    0
u    1
v    2
x    3
y    4
dtype: int64

to concat two diiferent data frames