NumPy is a genral-purpose array-processing package. It provides a high-performance multi-dimesional array object, and basic tools for working with these arrays.( to compute with and manupulate this array library in python.)

Array is a data structure that stores value of same data type. In python, this ia the main difference betn lists and arrays, While python list can contain values corresponding to diffrent data types, arrays in python can only contain values coreesponding to same data type.

In [1]:
import numpy as np

In [2]:
l1=[1,2,3]    #list
l2=[10,20,30]
array1=np.array(l1)
array1

array([1, 2, 3])

1D array above

In [4]:
array1.shape

(3,)

In [4]:
array2=np.array(l2)
array2

array([10, 20, 30])

In [5]:
type(array2)

numpy.ndarray

In [6]:
array3=(1,2,3)

In [7]:
type(array3)

tuple

In [9]:
array3=np.array([1,2,3])

In [10]:
type(array3)

numpy.ndarray

In [12]:
array4=np.array([[1,2,3],[10,20,30],[100,200,300]])

In [13]:
print(array4)

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]]


In [5]:
#array4.reshape(3,4)

In [14]:
array4.shape

(3, 3)

## ARange(Array Range)

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
array5=np.arange(1,10).reshape(3,3) #using reshape function we passed the value inside and reshape the array

In [17]:
array5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.arange(26)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [19]:
array6=np.arange(1,26).reshape(5,5)

In [20]:
array6

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [23]:
array7=np.arange(2,51,2).reshape(5,5)

In [24]:
array7

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [25]:
array8=np.arange(1,51).reshape(5,10)

In [26]:
array8

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [30]:
array9=np.arange(1,7).reshape(2,3)

In [31]:
array9*7

array([[ 7, 14, 21],
       [28, 35, 42]])

In [6]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [2]:

arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [3]:
#copy() and broadcasting
arr[3:]=100
arr

array([  1,   2,   3, 100, 100, 100])

In [4]:
arr1=arr

In [5]:
arr1[3:]=500
print(arr1)

[  1   2   3 500 500 500]


In [6]:
arr #Here arr is also getting updated with arr1 this is called as Reference Type
    #(i.e., if we change one variable it will afect the others)

array([  1,   2,   3, 500, 500, 500])

In [7]:
#to prevent this
arr1=arr.copy()

In [8]:
print(arr)
arr1[3:]=1000
print(arr1)

[  1   2   3 500 500 500]
[   1    2    3 1000 1000 1000]


In [32]:
arr=np.zeros([3,3])

In [33]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
arr=np.ones([3,3])

In [35]:
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [9]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Diagonal matrix add,sub,mul,div

In [36]:
arr=np.eye(5)

In [37]:
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
arr=np.eye(3)

In [39]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
arr=np.arange(1,7).reshape(2,3)

In [41]:
arr*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [42]:
arrr=np.arange(1,12,2).reshape(2,3)

In [43]:
arrr

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [44]:
arr+arrr

array([[ 2,  5,  8],
       [11, 14, 17]])

In [46]:
arr-arrr

array([[ 0, -1, -2],
       [-3, -4, -5]])

In [47]:
arr*arrr

array([[ 1,  6, 15],
       [28, 45, 66]])

In [48]:
arr/arrr

array([[1.        , 0.66666667, 0.6       ],
       [0.57142857, 0.55555556, 0.54545455]])

In [59]:
ar1=np.arange(1,51).reshape(5,10)
ar2=np.arange(1,11).reshape(2,5)

In [60]:
ar1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [61]:
ar3=ar1.T #.T is use for transpose

In [62]:
ar3

array([[ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43],
       [ 4, 14, 24, 34, 44],
       [ 5, 15, 25, 35, 45],
       [ 6, 16, 26, 36, 46],
       [ 7, 17, 27, 37, 47],
       [ 8, 18, 28, 38, 48],
       [ 9, 19, 29, 39, 49],
       [10, 20, 30, 40, 50]])

In [63]:
np.dot(ar1,ar3) #dot product original * transpose

array([[  385,   935,  1485,  2035,  2585],
       [  935,  2485,  4035,  5585,  7135],
       [ 1485,  4035,  6585,  9135, 11685],
       [ 2035,  5585,  9135, 12685, 16235],
       [ 2585,  7135, 11685, 16235, 20785]])

In [64]:
ar4=ar2.T

In [65]:
ar4

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [66]:
np.dot(ar2,ar4)

array([[ 55, 130],
       [130, 330]])

In [4]:
import numpy as np
a1=[1,2,3]
a2=[10,20,30]
a3=[100,200,300]
ar1=np.array([a1,a2,a3])

In [5]:
print(ar1)

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]]


In [8]:
ar1.shape

(3, 3)

In [49]:
print(np.alen(ar1))
print(np.exp(ar1))
print(np.sqrt(ar1))

3
[[2.71828183e+000 7.38905610e+000 2.00855369e+001]
 [2.20264658e+004 4.85165195e+008 1.06864746e+013]
 [2.68811714e+043 7.22597377e+086 1.94242640e+130]]
[[ 1.          1.41421356  1.73205081]
 [ 3.16227766  4.47213595  5.47722558]
 [10.         14.14213562 17.32050808]]


In [9]:
np.mean(ar1)

74.0

In [11]:
np.sum(ar1)

666

In [12]:
ar1.sum(0) #column wise

array([111, 222, 333])

In [13]:
ar1.sum(1)

array([  6,  60, 600])

In [14]:
ar1.mean(0)

array([ 37.,  74., 111.])

## Concept of slicing

In [15]:
ar=np.arange(1,26).reshape(5,5)

In [16]:
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [17]:
ar[0]

array([1, 2, 3, 4, 5])

In [19]:
ar[1:4]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [21]:
ar[:,1] #[row,column]

array([ 2,  7, 12, 17, 22])

In [22]:
ar[:,[1]]

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

In [24]:
ar[:,2:5]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [25]:
ar[:,1:]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [27]:
ar[1:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [28]:
ar[2,2]

13

In [29]:
ar[2:4,2:4]

array([[13, 14],
       [18, 19]])

In [30]:
ar[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [31]:
ar[3:,3:]

array([[19, 20],
       [24, 25]])

In [32]:
ar[2:4,2:]

array([[13, 14, 15],
       [18, 19, 20]])

In [34]:
ar[1::2] #2 is the step size ie third argument

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])

In [35]:
ar[:,0:3:2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

array name[start:end:step size]

In [40]:
ar[1::2,1:4:]

array([[ 7,  8,  9],
       [17, 18, 19]])

In [41]:
ar[3:5:,0:3:2]

array([[16, 18],
       [21, 23]])

## 3D Array

In [43]:
np.arange(1,13).reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [44]:
np.arange(1,25).reshape(4,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

## Random

### Rand

Create an array of the given shape and populate it with random sample from a uniform distribution over(0,1)

In [50]:
import numpy as np

In [51]:
np.random.rand(5) #rand fuctn gives values between 0 and 1

array([0.13848954, 0.68381102, 0.07582232, 0.85719598, 0.88745702])

In [52]:
np.random.rand(5,5)

array([[0.54667446, 0.16532899, 0.95726428, 0.91409326, 0.09006215],
       [0.02615773, 0.76084857, 0.78391583, 0.09046839, 0.45710982],
       [0.85868538, 0.04247088, 0.68978818, 0.92596816, 0.54509409],
       [0.60200221, 0.35303947, 0.23135558, 0.69284615, 0.16538005],
       [0.1714203 , 0.12520817, 0.93700414, 0.05667997, 0.78620214]])

In [53]:
from numpy.random import rand

In [55]:
rand(3)

array([0.06179317, 0.45333315, 0.01774808])

### Randn

In [56]:
np.random.randn(5) #between +3 and -3

array([ 1.11305778, -1.50317033,  0.05080414, -0.14017886, -0.7456448 ])

In [57]:
np.random.randn(5,5)

array([[-0.46290966, -0.47021205,  1.63023893,  0.38212854, -1.00446578],
       [ 0.0942088 ,  0.32305779,  0.53104558,  0.52319588, -1.10693482],
       [-0.32908901, -1.30700294,  0.34359698,  1.35282769,  1.59654226],
       [ 0.05080634,  0.11199433, -2.32225987, -1.55901158,  0.38934388],
       [-2.20165463,  0.99113222, -0.39482321,  0.33488602, -0.77367722]])

### Randint

Return a random integer from low to high

In [58]:
np.random.randint(1,100)

5

In [59]:
np.random.randint(1,100,10)

array([29,  9,  6, 43, 47, 29, 46, 56,  8, 64])

In [61]:
np.random.normal(1,20,3)

array([  3.45421466, -30.44978356,  -5.27769704])

In [67]:
a=np.random.randint(1,50,10)
a

array([11, 26, 35, 45, 48, 47, 49, 32, 21, 31])

In [63]:
a1=np.random.randint(1,50,5)

In [68]:
b=np.random.randint(1,50,10)
b

array([23, 41, 38, 15, 14, 23, 30, 29, 16, 13])

In [69]:
a+b

array([34, 67, 73, 60, 62, 70, 79, 61, 37, 44])

In [70]:
np.maximum(a,b)

array([23, 41, 38, 45, 48, 47, 49, 32, 21, 31])

In [71]:
a=np.array([True,False,True])

In [72]:
b=np.array([True,True,True])

In [73]:
c=np.array([False,False,False])

In [74]:
a.any() #if any one value in array a is true then it will give true

True

In [75]:
c.any()

False

In [76]:
a.all() #all values must be true, then true else false

False

In [77]:
b.all()

True

## Where Function

In [78]:
a1=np.array([1,2,3])
a2=np.array([100,200,300])
a3=np.array([True,False,True])

np.where(condition,true,false)

In [79]:
np.where(a3,a1,a2)

array([  1, 200,   3])

In [80]:
np.where(a3,a2,a1)

array([100,   2, 300])

In [84]:
aa=np.array([1,2,3,4]).reshape(2,2)
bb=np.array([10,20,30,40]).reshape(2,2)
cc=np.array([True,False,True,False]).reshape(2,2)

In [85]:
np.where(cc,aa,bb)

array([[ 1, 20],
       [ 3, 40]])

In [86]:
cc

array([[ True, False],
       [ True, False]])